-- Fresh Supabase project: core table + indexes + RLS + storage for AutoSell Ghana web app.
-- Run in Supabase SQL Editor (Dashboard → SQL → New query) as a single script.
--
-- After this:
-- 1. If NEXT_PUBLIC_LISTING_STATUSES lists more than "completed", edit the policy
--    "Public read published listings" below so `status` matches (same comma-separated ideas).
-- 2. Set SUPABASE_SERVICE_ROLE_KEY on the server for /api/car-submissions and /api/admin/*.
-- 3. Optional: CAR_SUBMISSIONS_YEAR_COLUMN=year_numeric — run scripts/supabase-year_numeric.sql
--    after this script if you want SQL-side year filters.

-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------
create table if not exists public.car_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  car_make text not null,
  car_model text not null,
  year text not null,
  year_numeric integer,
  price numeric not null,
  mileage integer not null,
  location text not null,
  package_type text not null,
  car_condition text not null,
  car_description text not null,
  seller_name text not null,
  seller_phone text not null,
  seller_email text,
  preferred_contact text not null,
  additional_info text,
  status text not null default 'new',
  notes text,
  photos jsonb,
  photo_metadata jsonb,
  transmission text,
  fuel_type text,
  paystack_reference text,
  paystack_payment_status text,
  constraint car_submissions_package_type_check check (package_type in ('free', 'premium', 'complete'))
);

comment on table public.car_submissions is 'Car listing submissions and published listings (status-driven).';

-- ---------------------------------------------------------------------------
-- Indexes (listings + admin ordering)
-- ---------------------------------------------------------------------------
create index if not exists idx_car_submissions_status_created
  on public.car_submissions (status, created_at desc);

create index if not exists idx_car_submissions_car_make on public.car_submissions (car_make);
create index if not exists idx_car_submissions_location on public.car_submissions (location);
create index if not exists idx_car_submissions_price on public.car_submissions (price);

create index if not exists idx_car_submissions_year_numeric on public.car_submissions (year_numeric);
create index if not exists idx_car_submissions_transmission on public.car_submissions (transmission);
create index if not exists idx_car_submissions_fuel_type on public.car_submissions (fuel_type);

-- ---------------------------------------------------------------------------
-- updated_at trigger (app also sends updated_at on admin save; trigger keeps DB honest)
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = coalesce(new.updated_at, now());
  return new;
end;
$$;

drop trigger if exists car_submissions_set_updated_at on public.car_submissions;
create trigger car_submissions_set_updated_at
  before update on public.car_submissions
  for each row
  execute procedure public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS: anon/authenticated = public site + browser sell form (storage only).
-- Inserts/updates for submissions go through Next.js + service role (bypasses RLS).
-- ---------------------------------------------------------------------------
alter table public.car_submissions enable row level security;

drop policy if exists "Public read published listings" on public.car_submissions;
-- Default app env: NEXT_PUBLIC_LISTING_STATUSES=completed — only those rows are public.
create policy "Public read published listings"
  on public.car_submissions
  for select
  to anon, authenticated
  using (status in ('completed'));

-- No INSERT/UPDATE/DELETE policies for anon/authenticated on this table:
-- public inserts use POST /api/car-submissions (service role).
-- admin uses GET/PATCH /api/admin/submissions (service role).

-- ---------------------------------------------------------------------------
-- Storage: public bucket + anon uploads under submissions/ (SellWizard)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit)
values ('car-photos', 'car-photos', true, 52428800)
on conflict (id) do update set public = excluded.public;

drop policy if exists "car-photos public read" on storage.objects;
create policy "car-photos public read"
  on storage.objects
  for select
  to public
  using (bucket_id = 'car-photos');

drop policy if exists "car-photos anon insert submissions" on storage.objects;
create policy "car-photos anon insert submissions"
  on storage.objects
  for insert
  to anon, authenticated
  with check (
    bucket_id = 'car-photos'
    and name like 'submissions/%'
  );
