-- Car rentals feature: rental_partners + rental_listings tables, RLS, storage policy.
-- Run in Supabase SQL Editor (Dashboard → SQL → New query) as a single script,
-- after supabase-fresh-car_submissions.sql has already been applied.
--
-- After this:
-- 1. If NEXT_PUBLIC_RENTAL_LISTING_STATUSES lists more than "active", edit the policy
--    "Public read active rental listings" below so `status` matches.
-- 2. SUPABASE_SERVICE_ROLE_KEY (already required for car_submissions) is reused for
--    /api/rental-partners and /api/admin/rental-*.

-- ---------------------------------------------------------------------------
-- Table: rental_partners (one row per rental business)
-- ---------------------------------------------------------------------------
create table if not exists public.rental_partners (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  business_name text not null,
  contact_name text not null,
  contact_phone text not null,
  contact_email text,
  whatsapp_number text,
  location text not null,
  business_description text,
  status text not null default 'pending',
  notes text,
  -- Placeholder monetization columns, unused this pass (no app code reads/writes these yet).
  subscription_tier text,
  subscription_status text,
  paystack_customer_code text,
  constraint rental_partners_status_check check (status in ('pending', 'approved', 'rejected'))
);

comment on table public.rental_partners is 'Rental business partners (status-driven approval, fleet owned via rental_listings).';

create index if not exists idx_rental_partners_status_created
  on public.rental_partners (status, created_at desc);

drop trigger if exists rental_partners_set_updated_at on public.rental_partners;
create trigger rental_partners_set_updated_at
  before update on public.rental_partners
  for each row
  execute procedure public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Table: rental_listings (one row per rental vehicle, FK to rental_partners)
-- ---------------------------------------------------------------------------
create table if not exists public.rental_listings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  partner_id bigint not null references public.rental_partners (id) on delete cascade,
  car_make text not null,
  car_model text not null,
  year text not null,
  year_numeric integer,
  vehicle_category text,
  transmission text,
  fuel_type text,
  seats integer,
  daily_rate numeric not null,
  with_driver_available boolean not null default false,
  self_drive_available boolean not null default true,
  location text not null,
  description text,
  status text not null default 'pending',
  notes text,
  photos jsonb,
  photo_metadata jsonb,
  -- Placeholder monetization columns, unused this pass.
  featured boolean not null default false,
  paystack_reference text,
  constraint rental_listings_status_check check (status in ('pending', 'active', 'rejected', 'archived'))
);

comment on table public.rental_listings is 'Rental vehicles owned by a rental_partners row (status-driven, partner status also gates visibility).';

create index if not exists idx_rental_listings_status_created
  on public.rental_listings (status, created_at desc);
create index if not exists idx_rental_listings_partner_id on public.rental_listings (partner_id);
create index if not exists idx_rental_listings_car_make on public.rental_listings (car_make);
create index if not exists idx_rental_listings_location on public.rental_listings (location);
create index if not exists idx_rental_listings_daily_rate on public.rental_listings (daily_rate);
create index if not exists idx_rental_listings_year_numeric on public.rental_listings (year_numeric);

drop trigger if exists rental_listings_set_updated_at on public.rental_listings;
create trigger rental_listings_set_updated_at
  before update on public.rental_listings
  for each row
  execute procedure public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.rental_partners enable row level security;
alter table public.rental_listings enable row level security;

-- No public SELECT policy on rental_partners at all: partner contact/internal
-- notes are only ever exposed to the client via an inner join from rental_listings.

drop policy if exists "Public read active rental listings" on public.rental_listings;
-- Default app env: NEXT_PUBLIC_RENTAL_LISTING_STATUSES=active — only those rows are public.
create policy "Public read active rental listings"
  on public.rental_listings
  for select
  to anon, authenticated
  using (status in ('active'));

-- No INSERT/UPDATE/DELETE policies for anon/authenticated on either table:
-- public signup uses POST /api/rental-partners (service role).
-- admin uses /api/admin/rental-partners* and /api/admin/rental-listings* (service role).

-- ---------------------------------------------------------------------------
-- Storage: reuse existing car-photos bucket under a new rentals/ prefix.
-- ---------------------------------------------------------------------------
drop policy if exists "car-photos anon insert rentals" on storage.objects;
create policy "car-photos anon insert rentals"
  on storage.objects
  for insert
  to anon, authenticated
  with check (
    bucket_id = 'car-photos'
    and name like 'rentals/%'
  );
